openapi: 3.0.0
info:
  title: OpenAPI test
  version: 1.0.0
  description: |
    A test OpenAPI specification for practicing OpenAPI tools.
    Based on [Yandex Dictionary API](http://api.yandex.ru/dictionary).
servers:
  - url: https://dictionary.yandex.net/api/v1/dicservice.json
paths:
  /lookup:
    get:
      summary: Look up translations
      description: Get all available translations of a word or phrase.
      parameters:
        - name: lang
          in: query
          required: true
          schema:
            type: string
            example: en-ru
          description: The language pair.
        - name: text
          in: query
          required: true
          schema:
            type: string
            example: time
          description: The text to translate.
      responses:
        '200':
          description: Translated word or phrase with usage examples and meaning explanation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/translation'
components:
  schemas:
    translation:
      $ref: './schemas/translation.yml'
  securitySchemes:
    key:
      type: apiKey
      description: API key to authorize requests.
      name: key
      in: query