openapi: 3.0.0
info:
  title: OpenAPI test
  version: 1.0.0
  description: |
    A test OpenAPI specification for practicing OpenAPI tools.
    Based on [Yandex Dictionary API](http://api.yandex.ru/dictionary).
servers:
  - url: https://dictionary.yandex.net/api/v1/dicservice.json
paths:
  /lookup:
    $ref: './paths/lookup.yml'
components:
  schemas:
    translation:
      $ref: './schemas/translation.yml'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: API key to authorize requests.
      name: key
      in: query

security:
  - ApiKeyAuth: []