name: Validate OpenAPI Schema

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install swagger-cli
      run: npm install -g swagger-cli

    - name: Validate OpenAPI schema
      run: swagger-cli validate openapi.yaml